Add Dockerfile + upgrade composer + upgrade php to 7.4 + fix
akeneo/api-php-client pull request #212
Opened 2022-01-20 16:40 UTC by tomglvng

2022-01-20 16:59 UTC, AymericPlanche reviewed
You need to update the [.circleci/config.yml](https://github.com/akeneo/api-php-client/blob/master/.circleci/config.yml#L6) and build the image to run the tests

2022-01-20 16:59 UTC, LevFlavien requested changes
Shouldn't CI use the same Dockerfile as well?

2022-01-20 17:04 UTC, tomglvng commented
> You need to update the [.circleci/config.yml](https://github.com/akeneo/api-php-client/blob/master/.circleci/config.yml#L6) and build the image to run the tests. No ? thinking

Oups! My bad!

2022-01-25 08:14 UTC, AymericPlanche approved these changes

2022-01-25 08:56 UTC, LevFlavien approved these changes

2022-01-25 10:15 UTC, tomglvng commented on .circleci/config.yml
> +                command: sudo chmod -R 777 ../project
Yes, I tried to change user group, without success :(

2022-01-25 10:16 UTC, merged