Implement SystemInformationApi for the GET endpoint /api/rest/v1/system-information
akeneo/api-php-client pull request #279
Opened 2023-11-07 12:46 UTC by ConstantBqt

Get the data from this endpoint https://api.akeneo.com/api-reference.html#get_system_information 

Available in PIM versions: 6.0, 7.0 and SaaS

2024-01-16 04:15 UTC, ConstantBqt commented
What are the next steps to get this PR approved ?

2024-02-14 16:00 UTC, ConstantBqt commented
Hello @tomglvng, 
I saw your name as reviewer for another PR of this repository. Could you please review this PR when you get a chance ? 
Thanks a lot !

2024-03-15 15:15 UTC, tomglvng commented
> Hello @tomglvng, I saw your name as reviewer for another PR of this repository. Could you please review this PR when you get a chance ? Thanks a lot!

*Hello @ConstantBqt ,*

*Thank you so much for your contribution! To continue the merge process, we would need you to sign our Contributor License Agreement kindly. Please find it here: https://www.akeneo.com/contributor-license-agreement/*

*Looking forward to reading you,*

*The Akeneo development team*

2024-03-15 15:18 UTC, tomglvng requested changes
Did you launch tests?
make tests

2024-03-15 15:18 UTC, tomglvng commented on src/Api/SystemInformationApi.php
You should add tests for this class. Get inspiration with spec/Api/AttributeGroupApiSpec.php

2024-03-21 22:24 UTC, ConstantBqt commented on src/Api/SystemInformationApi.php
Hi @tomglvng 
I added `SystemInformationApiSpec` and fix the `AkeneoPimClientSpec` in my last commit. 
The result of `make tests` is successful 

Thanks 🙏

2024-05-13 11:49 UTC, lasdou commented
Hello, Any updates regarding this PR @tomglvng ? I would be interested by this new endpoint too. Thanks ;-)

2024-05-13 11:54 UTC, lasdou commented
CI is green so merging it should be ok. Waiting for @tomglvng review

2024-09-27 12:54 UTC, tomglvng commented
https://github.com/akeneo/api-php-client/pull/292

2024-09-27 12:56 UTC, tomglvng commented
Hello @ConstantBqt , SOrry for the delay. I created a PR to merge your contribution. I'm waiting for the review. Could you have a look @lasdou ?

2024-09-27 13:48 UTC, tomglvng commented
@ConstantBqt merged! Thanks for your contribution ;)

2024-09-27 13:48 UTC, closed without merging